authenticate/urls.py
from django.urls import path
from . import views

app_name = 'authenticate'
urlpatterns = [
	path('register', views.register, name = 'register'),
	path('login', views.login_view, name = 'login'),
	path('logout', views.logout_view, name = 'logout'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
	path('dashboard', views.dashboard, name = 'dashboard'),
	path("store/<str:category>/", views.store, name = 'store'),
	path("product_view/<int:id>/", views.product_view, name = 'product_view'),
	path('checkout/<int:id>/', views.checkout, name = 'checkout'),
	path('update_item', views.updateItem, name = 'updateItem'),
	path('cart', views.cart, name = 'cart'),
	path("process_order", views.processOrder, name = 'processOrder'),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
	path('', views.index, name = 'index'),
	path("store/<str:category>/", views.store, name = 'store'),
	path("product_view/<int:id>/", views.product_view, name = 'product_view'),
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('index.urls')),
	path('dashboard/', include('dashboard.urls')),
	path('authenticate/', include('authenticate.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/templates/index/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>{% block title %}{% endblock %}</title>
	{% block scripts %}
	{% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard\\css\\base.css' %}">
	<script src="https://kit.fontawesome.com/250a986bc8.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script type="text/javascript">
		var user = '{{request.user}}';
	</script>
</head>
<body>
	<div id="container">
	<div id="main">
	<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #e3f2fd;">
		<div class="container">
		<a class="navbar-brand mt-1 h1" href="{% url 'index:index' %}">Xeon</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
				<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
					<li class="nav-item active">
					<a class="nav-link" href="{% url 'authenticate:register' %}">Sign up</a>
					</li>
					<li class="nav-item active">
					<a class="nav-link" href="{% url 'authenticate:login' %}">Login</a>
					</li>
					<li class="nav-item active dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<table>
								<tr>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Food' %}">Food</a></td>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Electronics' %}">Electronics</a></td>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Tools' %}">Tools and Home improvement</a></td>
								</tr>
								<tr>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Drink' %}">Drink</a></td>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Computers' %}">Computers</a></td>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Home_kitchen' %}">Home and Kitchen</a></td>
									
								</tr>
								<tr>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Toys' %}">Toys</a></td>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Automotive' %}">Automotive</a></td>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Sports' %}">Sports and Outdoors</a></td>
								</tr>
								<tr>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Apparel' %}">Apparel</a></td>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Beauty' %}">Beauty</a></td>
									<td><a class="dropdown-item" href="{% url 'index:store' 'Health' %}">Health</a></td>
								</tr>
							</table>
						</div>
					</li>
				</ul>
				<div class="navbar-nav mr-auto">
					<a class="nav-link active h5" href="#">Welcome</a>
				</div>
				<form class="form-inline my-2 my-lg-0">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
					<a href="{% url 'dashboard:cart' %}" style="margin-left: 10px;"><i class="fas fa-shopping-cart fa-lg"></i></a>
				</form>
		</div>
		
		</div>
	</nav>
	{% block body %}
	{% endblock %}
</div>
</div>
	<footer class="footer">
		<div class="container">
			<p>© 2020 Xeon® Global Inc.</p>
			<p><a href="#" style="color: white; padding-right: 10px">Terms of Service</a>
			<a href="#" style="color: white; padding-right: 10px; padding-left: 10px">Privacy Policy</a>
			<a href="#" style="color: white; padding-left: 10px">Accessibility</a></p>
		</div>
	</footer>
	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'dashboard\\js\\cart.js' %}"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	{% block script %}{% endblock %}
</html>

index/templates/index/index.html
{% extends 'index\\base.html' %}
{% load static %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static 'index\\css\\index_1.css' %}">

{% endblock %}
{% block body %}
	<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
		<div class="carousel-inner">
			<div class="carousel-item active" data-interval="2000">
				<img src="{% static 'index\\images\\11.jpg' %}" class="d-block w-100">
				<div class="carousel-caption d-flex h-100 align-items-center justify-content-center">
				<h1>Purchase with huge discounts</h1>
				</div>
			</div>
			<div class="carousel-item" data-interval="2000">
				<img src="{% static 'index\\images\\22.jpg' %}" class="d-block w-100">
				<div class="carousel-caption d-flex h-100 align-items-center justify-content-center">
				<h1>Fresh products and free deliver</h1>
				</div>
			</div>
			<div class="carousel-item" data-interval="2000">
				<img src="{% static 'index\\images\\44.jpg' %}" class="d-block w-100">
				<div class="carousel-caption d-flex h-100 align-items-center justify-content-center">
				<h1>Receive on time</h1>
				</div>
			</div>
		</div>
		<a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

<div class="container">
	<section class="for-cards">
		<div class="row">
			{% if products %}
			{% for product in products %}
			<div class="col col-sm-6 col-md-4 col-lg-3">
				<div class="card-header">
					<h4>{{product.name.capitalize}}</h4>
				</div>
				<div class="card-image">
					<img class='thumbnail' src="{{product.image.url}}">
				</div>
				<div class="card-body">
					<h3>${{product.price|floatformat:2}}</h3>
				</div>
				<div class="card-footer">
					<a class="btn btn-primary" href="{% url 'index:product_view' product.id %}">View</a>
					<button class="btn btn-outline-success update-cart" data-product="{{product.id}}" data-action="add" data-url="{% url 'dashboard:updateItem' %}" data-csrftoken="{{ csrf_token }}">Add to cart</button>
				</div>
			</div>
			{% endfor %}
			{% endif %}
		</div>
	</section>
</div>
	<div class="foot">
		<div class="container" id="table">
			<table id="tbl" class="justify-content-center nav-fill" align="center">
				<tr>
					<th><br>Get to know us</th>
					<th><br>Xeon payment products</th>
					<th><br>Let us help you</th>
				</tr>
				<tr>
					<td><a href="#" style="color: white">Careers</td></a>
					<td><a href="#" style="color: white">Xeon Business card</td></a>
					<td><a href="#" style="color: white">Xeon and COVID-19</td></a>
				</tr>
				<tr>
					<td><a href="#" style="color: white">Blog</td></a>
					<td><a href="#" style="color: white">Reload your Balance</td></a>
					<td><a href="#" style="color: white">Your account</td></a>
				</tr>
				<tr>
					<td><a href="#" style="color: white">About Xeon</td></a>
					<td><a href="#" style="color: white">Xeon currency converter</td></a>
					<td><a href="#" style="color: white">Your orders</td></a>
				</tr>
				<tr>
					<td><a href="#" style="color: white">About Relations</td></a>
					<td><a href="#" style="color: white">Shop with points</td></a>
					<td><a href="#" style="color: white">Return and replacements</td></a>
				</tr>
				<tr>
					<td><a href="#" style="color: white">About Devices</td></a>
					<td><a href="#" style="color: white">Help</td></a>
				</tr>
			</table>
		</div>
	</div>
{% endblock %}

index/templates/index/product_view.html
{% extends 'index\\base.html' %}
{% load static %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static 'index\\css\\product_view.css' %}">
{% endblock %}
{% block body %}
<div class="container">
	<div class="product">
		{% if product %}
		<div class="product-image">
			<img class="thumbnail" src="{{product.image.url}}">
		</div>
		<div class="product-body">
			<div class="product-header">
				{{ product.name.capitalize }}<br>
				${{ product.price|floatformat:2 }}
			</div>
			<div class='product-description'>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla viverra nulla 
					a nisl tincidunt viverra. Duis laoreet, enim quis fermentum placerat, velit purus 
					accumsan turpis, at ultricies mi arcu ac nulla. In quis consequat nibh, eu varius enim.
					 In eu gravida neque, id posuere mi. Nam scelerisque arcu a luctus volutpat. Integer 
					 volutpat tristique mi, vel euismod ante consequat quis. In convallis augue sed 
					 pellentesque rhoncus. Nulla luctus elementum enim. Morbi enim ipsum, viverra quis magna
					  non, elementum semper risus. Phasellus a libero non turpis molestie consectetur vel eget
					   purus. Curabitur tincidunt nisl quis elementum luctus. Morbi bibendum quam ac augue bibendum,
					    at faucibus diam mollis. Nunc venenatis justo risus, id tristique ante scelerisque in. 
						Nullam luctus est eu laoreet pretium. Vestibulum ultrices libero vitae enim faucibus varius.

				</p>
			</div>
			<div class="product-action">
				<button class="btn btn-outline-success update-cart" data-product="{{product.id}}" data-action="add" data-url="{% url 'dashboard:updateItem' %}" data-csrftoken="{{ csrf_token }}">Add to cart</button>
			</div>
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

index/templates/index/store.html
{% extends 'index\\base.html' %}
{% load static %}
{%block scripts %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard\\css\\dashboard.css' %}">
{% endblock %}
{% block body %}
<div class="container">
	{% for message in messages %}
		<div class="alert alert-success" role="alert" style="text-align: center">
  			{{message}}
		</div>
	{% endfor %}
	<section class="for-cards">
		<div class="row">
			{% if products %}
			{% for product in products %}
			<div class="col col-sm-6 col-md-4 col-lg-3">
				<div class="card-header">
					<h4>{{product.name.capitalize}}</h4>
				</div>
				<div class="card-image">
					<img class='thumbnail' src="{{product.image.url}}">
				</div>
				<div class="card-body">
					<h3>${{product.price|floatformat:2}}</h3>
				</div>
				<div class="card-footer">
					<a class="btn btn-primary" href="{% url 'index:product_view' product.id %}">View</a>
					<button class="btn btn-outline-success update-cart" data-product="{{product.id}}" data-action="add" data-url="{% url 'dashboard:updateItem' %}" data-csrftoken="{{ csrf_token }}">Add to cart</button>
				</div>
			</div>
			{% endfor %}
			{% endif %}
		</div>
	</section>
</div>
{% endblock %}