authenticate/urls.py
from django.urls import path
from . import views

app_name = 'authenticate'
urlpatterns = [
	path('register', views.register, name = 'register'),
	path('login', views.login_view, name = 'login'),
	path('logout', views.logout_view, name = 'logout'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
	path('dashboard', views.dashboard, name = 'dashboard'),
	path("store/<str:category>/", views.store, name = 'store'),
	path("product_view/<int:id>/", views.product_view, name = 'product_view'),
	path('checkout/<int:id>/', views.checkout, name = 'checkout'),
	path('update_item', views.updateItem, name = 'updateItem'),
	path('cart', views.cart, name = 'cart'),
	path("process_order", views.processOrder, name = 'processOrder'),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
	path('', views.index, name = 'index'),
	path("store/<str:category>/", views.store, name = 'store'),
	path("product_view/<int:id>/", views.product_view, name = 'product_view'),
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('index.urls')),
	path('dashboard/', include('dashboard.urls')),
	path('authenticate/', include('authenticate.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
	name = models.CharField(max_length = 150, null=True)
	email = models.EmailField(null=True)

	def __str__(self):
		return self.user.username


class Category(models.Model):
	name = models.CharField(max_length = 150, null=True)
	
	def __str__(self):
		return self.name

class Product(models.Model):
	name = models.CharField(max_length = 150, null=True)
	price = models.DecimalField(max_digits = 7, decimal_places=2)
	digital = models.BooleanField(default = False, null = True, blank=True)
	category = models.ManyToManyField(Category)
	image = models.ImageField(null=True, blank=True)


	def __str__(self):
		return self.name

class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete = models.CASCADE, null = True)
	date_ordered = models.DateTimeField(auto_now_add = True)
	complete = models.BooleanField(default = False, null = True, blank=False)
	transaction_id = models.CharField(max_length = 150, null=True)

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total

	def __str__(self):
		if self.customer:
			return f"Order {self.id}: {self.customer.name}"
		return "No orders"

class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete = models.SET_NULL, null = True, blank=True)
	order = models.ForeignKey(Order, on_delete = models.CASCADE, null = True, blank=True)
	date_added = models.DateTimeField(auto_now_add = True)
	quantity = models.IntegerField(default=0, blank=True, null=True)

	@property
	def get_total(self):
		total = self.product.price * self.quantity
		return total

	def __str__(self):
		if self.order and self.order.customer:
			return f"{self.order.customer.name}: {self.product}"
		return "No order items"

class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete = models.CASCADE, null = True)
	order = models.ForeignKey(Order, on_delete = models.CASCADE, null = True)
	address = models.CharField(max_length = 150, null=False)
	city = models.CharField(max_length = 150, null=False)
	country = models.CharField(max_length = 150, null=False)
	zipcode = models.CharField(max_length = 150, null=False)
	date_added = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.address


dashboard/views.py
from django.shortcuts import render, redirect, reverse
from .models import *
import json
import datetime
from django.http import JsonResponse


def dashboard(request):
	if not request.user.is_authenticated:
		return redirect(reverse('authenticate:login'))
	customer = request.user.customer
	if customer.order_set.filter(complete=False):
		order_num = customer.order_set.filter(complete=False).first().get_cart_items
	else:
		order_num = 0
	querysets = []
	orders = Order.objects.filter(customer=customer, complete=True).all()
	for queryset in orders:
		querysets.append(queryset.orderitem_set.all())
	products = []
	for order in querysets:
		products.extend([item.product for item in order])
	if products == []:
		context = {'message':"You don't have completed and shipped orders yet.", 'order_num':order_num}
	else:
		context = {'products':products, 'order_num':order_num}
	return render(request, 'dashboard\\dashboard.html', context = context)


def store(request, category):
	if not request.user.is_authenticated:
		return redirect(reverse('authenticate:login'))
	customer = request.user.customer
	if customer.order_set.filter(complete=False):
		order_num = customer.order_set.filter(complete=False).first().get_cart_items
	else:
		order_num = 0
	if category == 'all':
		products = Product.objects.all()
		context = {'products':products, 'order_num':order_num}
		return render(request, 'dashboard\\store.html', context=context)
	if category=='Sports':
		category='Sports and Outdoors'
	elif category=='Home_kitchen':
		category='Home and Kitchen'
	elif category=='Tools':
		category='Tools and Home improvement'
	else:
		pass
	category = Category.objects.filter(name=category).first()
	products = Product.objects.filter(category=category.id)
	context = {'products':products, 'order_num':order_num}
	return render(request, 'dashboard\\store.html', context=context)


def product_view(request, id):
	if not request.user.is_authenticated:
		return redirect(reverse('authenticate:login'))
	customer = request.user.customer
	if customer.order_set.filter(complete=False):
		order_num = customer.order_set.filter(complete=False).first().get_cart_items
	else:
		order_num = 0
	product = Product.objects.filter(id=int(id)).first()
	context = {
	'product':product,
	'order_num':order_num
	}
	return render(request, 'dashboard\\product_view.html', context=context)


def checkout(request, id):
	if not request.user.is_authenticated:
		return redirect(reverse('authenticate:login'))
	customer = request.user.customer
	if customer.order_set.filter(complete=False):
		order_num = customer.order_set.filter(complete=False).first().get_cart_items
	else:
		order_num = 0
	order = Order.objects.filter(id=id).first()
	total_cost = order.get_cart_total
	items = order.orderitem_set.all()
	context = {
		'total_cost':total_cost,
		'items': items,
		'order_num':order_num
		}
	return render(request, 'dashboard\\checkout.html', context=context)


def cart(request):
	if not request.user.is_authenticated:
		return redirect(reverse('authenticate:login'))
	customer = request.user.customer
	if customer.order_set.filter(complete=False):
		order_num = customer.order_set.filter(complete=False).first().get_cart_items
	else:
		order_num = 0
	customer = request.user.customer
	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	items = order.orderitem_set.all()
	context = {'items':items, 'order':order, 'order_num':order_num}
	return render(request, 'dashboard\\cart.html', context)



def updateItem(request):
	if not request.user.is_authenticated:
		return redirect(reverse('authenticate:login'))
	if request.is_ajax() and request.method=='POST':
		product_id = request.POST['productId']
		action = request.POST['action']
		customer = request.user.customer
		product = Product.objects.filter(id=product_id).first()
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
		orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
		response = {'message':f"{product.name} is added to your cart!"}
		if action == 'add':
			orderItem.quantity = 1
		elif action == 'remove':
			orderItem.quantity -= 1
		elif action == 'increment':
			orderItem.quantity += 1
		else:
			response = {'message':"Invalid action"}
		orderItem.save()
		if orderItem.quantity <= 0:
			orderItem.delete()
		return JsonResponse(response, safe=False, status=200)
	else:
		return JsonResponse({'message':'Some error occured'}, safe=False, status=404)

def processOrder(request):
	if not request.user.is_authenticated:
		return redirect(reverse('authenticate:login'))
	data = json.loads(request.body)
	shipping = data['form']['shipping']
	transaction_id = datetime.datetime.now().timestamp()
	customer = request.user.customer
	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	total = float(data['form']['total'])
	order.transaction_id = transaction_id
	if float(total) == float(order.get_cart_total):
		order.complete = True
	order.save()
	if shipping==True:
		ShippingAddress.objects.create(
				customer=customer,
				order=order,
				address = data['shipping']['street'],
				city = data['shipping']['city'],
				zipcode = data['shipping']['zipcode'],
				country = data['shipping']['country'],
				)
	return JsonResponse('Payment complete!', safe=False)

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	{% block scripts %}
	{% endblock %}
	{% load static %}
	<script type="text/javascript">
		var user = '{{request.user}}';
	</script>
	<script src="https://kit.fontawesome.com/250a986bc8.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard\\css\\base.css' %}">
</head>
<body>
	<div id='container'>
	<div id="main">
	<nav class="navbar sticky-top navbar-expand-lg navbar-light">
		<div class="container">
		<a class="navbar-brand mb-0 h1" href="{% url 'dashboard:dashboard' %}">Xeon</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
				<a class="nav-link active" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
				</li>
				<li class="nav-item">
				<a class="nav-link active" href="{% url 'dashboard:store' 'all' %}">Store</a>
				</li>
				<li class="nav-item active dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<table>
								<tr>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Food' %}">Food</a></td>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Electronics' %}">Electronics</a></td>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Tools' %}">Tools and Home improvement</a></td>
								</tr>
								<tr>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Drink' %}">Drink</a></td>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Computers' %}">Computers</a></td>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Home_kitchen' %}">Home and Kitchen</a></td>
									
								</tr>
								<tr>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Toys' %}">Toys</a></td>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Automotive' %}">Automotive</a></td>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Sports' %}">Sports and Outdoors</a></td>
								</tr>
								<tr>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Apparel' %}">Apparel</a></td>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Beauty' %}">Beauty</a></td>
									<td><a class="dropdown-item" href="{% url 'dashboard:store' 'Health' %}">Health</a></td>
								</tr>
							</table>
						</div>
					</li>
			</ul>
			<form class="form-inline my-2 my-lg-0">
				<a href="{% url 'dashboard:cart' %}"><i class="fas fa-shopping-cart"></i><span class="badge badge-light">{% block order_num %}{% endblock %}</span></a>
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				<a class="nav-link" href="{% url 'authenticate:logout' %}">Logout</a>
			</form>
		</div>
		</div>
		</nav>
	{% block body %}
	{% endblock %}
	</div>
</div>
	<footer class="footer sticky-bottom">
		<div class="container">
			<p>© 2015 - 2020 Xeon® Global Inc.</p>
			<p><a href="#">Terms of Service</a>
			<a href="#">Privacy Policy</a>
			<a href="#">Accessibility</a></p>
		</div>
	</footer>
	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'dashboard\\js\\cart.js' %}"></script>
	{% block script %}
	{% endblock %}
</body>
</html>

dashboard/templates/dashboard/cart.html
{% extends 'dashboard\\base.html' %}
{% load static %}
{% block scripts %}
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard\\css\\cart.css' %}">
{% endblock %}
{% block order_num %}
{{order_num}}
{% endblock %}
{% block body %}
<div class="container">

	<div class="row justify-content-center">
		<div class="col-6" id="header">
		<h1>Cart</h1>
		</div>
		<div class="col-6" id="total">
			<h2>Items: {{order.get_cart_items}}</h2>
			<h2>Total: ${{order.get_cart_total|floatformat:2}}</h2>
			{% if order.get_cart_items > 0 %}
			<h3><a href="{% url 'dashboard:checkout' order.id %}" class="btn btn-primary">Proceed to payment <i class="fas fa-long-arrow-alt-right"></i></a></h3>
			{% endif %}
		</div>
	</div>
	<div class="row justify-content-center">
		{% for item in items %}
			<div class="col-12 col-sm-6 col-md-4">
				<div class="product">
					<div class="image">
						<h2>{{item.product.name.capitalize}}</h2>
						<img src="{{item.product.image.url}}" class="thumbnail" width="150px" height="150px">
					</div>
					<div class="product-header">
						<div id="quantity">
							<h5>Quantity: </h5>
							<h4>{{item.quantity}}</h4>
							<div id="icons">
								<span class="icon"><i class="fas fa-caret-up update-cart" data-product="{{item.product.id}}" data-action="increment" data-url="{% url 'dashboard:updateItem' %}" data-csrftoken="{{ csrf_token }}" style="color: #339af0;"></i></span>
								<span class="icon"><i class="fas fa-caret-down update-cart" data-product="{{item.product.id}}" data-action="remove" data-url="{% url 'dashboard:updateItem' %}" data-csrftoken="{{ csrf_token }}" style="color: #339af0;"></i></span>
							</div>
						</div>
						<h6>Price: ${{item.product.price|floatformat:2}}</h6>
					</div>
					<div class="product-body">
						<h4>Total: ${{item.get_total|floatformat:2}}</h3>
						<hr>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

dashboard/templates/dashboard/checkout.html
{% extends 'dashboard\\base.html' %}
{% load static %}
{% block scripts %}
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard\\css\\checkout.css' %}">
{% endblock %}
{% block order_num %}
{{order_num}}
{% endblock %}
{% block body %}

	<div class="container">
		<div class="alert alert-danger" role="alert"></div>
		<div id="all-items">
		<div class="total">
			<div class="cost">
				{% if total_cost %}
				<h2>Total: ${{total_cost|floatformat:2}}</h2>
				{% endif %}
			</div>
			<h2 style="margin-top: 25px;">Ordered items</h2>
			<i class="fas fa-angle-double-down"></i>
			<div class="items">
				{% for item in items %}
					<div class="item">
						<div class="image">
							<img src="{{item.product.image.url}}" class="thumbnail" width="90px" height="90px">
						</div>
						<div class="item-body">
							<div class="item-header">
								<h4>{{item.product.name.capitalize}} x{{item.quantity}}</h4>
							</div>
							<div class="item-footer">
								<h4 style="color: #2c5e8a;">${{item.get_total|floatformat:2}}</h4>
							</div>
						</div>
					</div>
					<hr>
				{% endfor %}
			</div>
		</div>
		<div id="inputs">
		<div id='address-form'>
			<form id="address">
				<label>Street address:</label>
				<input class="form-control" type="text" name="street" required>
				<br>
				<label>City/Town:</label>
				<input class="form-control" id="inputCity" type="text" name="city" required>
				<br>
				<label>Zipcode:</label>
				<input class="form-control" type="number" name="zipcode" required>
				<br>
				<label>Country:</label>
				<input class="form-control" type="text" name="country" required><br>
				<input id="continue" type="submit" class="btn btn-success" value = 'Continue'></input>
			</form>
		</div>
	
		<div id="paypal-button-container" style="display: none;"></div>
		</div>
	</div>
	</div>

{% endblock %}

{% block script %}
<script src="https://www.paypal.com/sdk/js?client-id=ATdN6B8gdPmKyoImhe8BzINztQVvVBjx3kmUBlao48p3FEv9dseo7PCbcBSxITAoF-G1eVLE5c3sJlHR&currency=USD"></script>
<script type="text/javascript">
	var total = '{{total_cost|floatformat:2}}';
	var csrftoken = '{{ csrf_token }}';
	var premise_url = "{% url 'dashboard:store' 'all' %}";
	var url = "{% url 'dashboard:processOrder' %}";
	var shipping = false;
	{% for item in items %}
		{% if item.product.digital == False %}
			shipping= true
		{% endif %}
	{% endfor %}
</script>
<script type="text/javascript" src="{% static 'dashboard\\js\\checkout.js' %}"></script>

{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard\\base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block order_num %}
{{order_num}}
{% endblock %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard\\css\\dashboard.css' %}">
{% endblock %}
{% block body %}
<div class="container">
	{% if message %}
			<div class="alert alert-danger" role="alert" style="text-align: center">
  				{{message}}
			</div>
	{% endif %}
</div>
<div class="container">
  <div id="head">
    <h2>Completed orders</h2>
  </div>
	<section class="for-cards">
    <div class="row">
      {% if products %}
      {% for product in products %}
      <div class="col col-sm-6 col-md-4 col-lg-3">
        <div class="card-head">
          <h4>{{product.name.capitalize}}</h4>
        </div>
        <div class="card-image">
          <img class='thumbnail' src="{{product.image.url}}" width="300px" height="300px">
        </div>
        <div class="card-body">
          <h3>${{product.price|floatformat:2}}</h3>
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </section>
</div>
{% endblock %}

dashboard/templates/dashboard/product_view.html
{% extends 'dashboard\\base.html' %}
{% load static %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static 'index\\css\\product_view.css' %}">
{% endblock %}
{% block order_num %}
{{order_num}}
{% endblock %}
{% block body %}
<div class="container">
	<div class="product">
		{% if product %}
		<div class="product-image">
			<img class="thumbnail" src="{{product.image.url}}">
		</div>
		<div class="product-body">
		<div class="product-header">
			{{ product.name.capitalize }}<br>
			${{ product.price|floatformat:2 }}
		</div>
		<div class='product-description'>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla viverra nulla 
					a nisl tincidunt viverra. Duis laoreet, enim quis fermentum placerat, velit purus 
					accumsan turpis, at ultricies mi arcu ac nulla. In quis consequat nibh, eu varius enim.
					 In eu gravida neque, id posuere mi. Nam scelerisque arcu a luctus volutpat. Integer 
					 volutpat tristique mi, vel euismod ante consequat quis. In convallis augue sed 
					 pellentesque rhoncus. Nulla luctus elementum enim. Morbi enim ipsum, viverra quis magna
					  non, elementum semper risus. Phasellus a libero non turpis molestie consectetur vel eget
					   purus. Curabitur tincidunt nisl quis elementum luctus. Morbi bibendum quam ac augue bibendum,
					    at faucibus diam mollis. Nunc venenatis justo risus, id tristique ante scelerisque in. 
						Nullam luctus est eu laoreet pretium. Vestibulum ultrices libero vitae enim faucibus varius.
			</p>
		</div>
		<div class="product-action">
			<button class="btn btn-outline-success update-cart" data-product="{{product.id}}" data-action="add" data-url="{% url 'dashboard:updateItem' %}" data-csrftoken="{{ csrf_token }}">Add to cart</button>
		</div>
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

dashboard/templates/dashboard/store.html
{% extends 'dashboard\\base.html' %}
{% load static %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard\\css\\dashboard.css' %}">
{% endblock %}
{% block order_num %}
{{order_num}}
{% endblock %}
{% block body %}
<div class="container">
	<section class="for-cards">
		<div class="row">
			{% if products %}
			{% for product in products %}
			<div class="col col-sm-6 col-md-4 col-lg-3">
				<div class="card-head">
					<h4>{{product.name.capitalize}}</h4>
				</div>
				<div class="card-image">
					<img class='thumbnail' src="{{product.image.url}}" width="300px" height="300px">
				</div>
				<div class="card-body">
					<h3>${{product.price|floatformat:2}}</h3>
				</div>
				<div class="card-foot">
					<a class="btn btn-primary" href="{% url 'dashboard:product_view' product.id %}">View</a>
					<button class="btn btn-outline-success update-cart" data-product="{{product.id}}" data-action="add" data-url="{% url 'dashboard:updateItem' %}" data-csrftoken="{{ csrf_token }}">Add to cart</button>
				</div>
			</div>
			{% endfor %}
			{% endif %}
		</div>
	</section>
</div>
{% endblock %}
{% block script %}
{% endblock %}